import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product.js';

dotenv.config();

// Combined product data from constants.ts and user's spreadsheet
const products = [
    // === Existing products from constants.ts ===
    {
        productId: 4,
        name: 'Cheek to Chic Blush',
        brand: 'Charlotte Tilbury',
        description: 'Two-tone blush for sculpting and highlighting.',
        price: 3320,
        rating: 4.5,
        reviews: 2345,
        image: 'https://m.media-amazon.com/images/I/412sUzOXpCL._SX522_.jpg',
        type: 'Blush',
        category: 'Cheeks',
        colors: [
            { name: 'Peach', hex: '#FFCBA4' },
            { name: 'Rose', hex: '#F33A6A' },
            { name: 'Coral Pink', hex: '#F88379' },
            { name: 'Mauve', hex: '#E0B0FF' },
        ],
    },
    {
        productId: 5,
        name: 'Cheek Heat Gel-Based Blush',
        brand: 'Maybelline New York',
        description: 'Buildable gel for a natural flush.',
        price: 747,
        rating: 4.2,
        reviews: 1892,
        image: 'https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/mby/mby57818/v/11.jpg',
        type: 'Blush',
        category: 'Cheeks',
        colors: [
            { name: 'Peach', hex: '#FFCBA4' },
            { name: 'Rose', hex: '#F33A6A' },
            { name: 'Coral Pink', hex: '#F88379' },
            { name: 'Mauve', hex: '#E0B0FF' },
        ],
    },
    {
        productId: 6,
        name: 'Tattoo Brow 36HR Eyebrow Pencil',
        brand: 'Maybelline New York',
        description: 'Long-lasting eyebrow pencil with spoolie.',
        price: 913,
        rating: 4.6,
        reviews: 2134,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1086317/CEoGk83p85-6902395829522_1.jpg',
        type: 'Eyebrow',
        category: 'Eyes',
        colors: [
            { name: 'Blonde', hex: '#C6A981' },
            { name: 'Light Brown', hex: '#9E7B54' },
            { name: 'Medium Brown', hex: '#6B4E32' },
            { name: 'Dark Brown', hex: '#3B2A1A' },
        ],
    },
    {
        productId: 7,
        name: 'Matte Revolution Lipstick',
        brand: 'Charlotte Tilbury',
        description: 'A classic matte lipstick for all occasions.',
        price: 2800,
        rating: 4.9,
        reviews: 6200,
        image: 'https://images-static.nykaa.com/media/catalog/product/5/8/58f72865060542728485_1.jpg?tr=w-344,h-344,cm-pad_resize',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        colors: [
            { name: 'Nude Pink', hex: '#C67B7B' },
            { name: 'Classic Red', hex: '#A52A2A' },
            { name: 'Berry', hex: '#8A3d54' },
            { name: 'Deep Plum', hex: '#5A203C' },
            { name: 'Coral', hex: '#FF7F50' },
            { name: 'Fuchsia', hex: '#FF00FF' },
        ],
    },
    {
        productId: 8,
        name: 'Absolute Skin Natural Mousse',
        brand: 'Lakme',
        description: 'Feather-light mousse for a natural matte finish.',
        price: 850,
        rating: 4.4,
        reviews: 3200,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/891950/2sNnOoF_P3-891950_1.jpg',
        type: 'Foundation',
        category: 'Face',
        colors: [
            { name: 'Ivory Fair', hex: '#F3D9C6' },
            { name: 'Rose Fair', hex: '#E6BBA9' },
            { name: 'Golden Medium', hex: '#D1A276' },
            { name: 'Almond Honey', hex: '#B58969' },
        ],
    },
    {
        productId: 9,
        name: '9 to 5 Primer + Matte Lipstick',
        brand: 'Lakme',
        description: 'Long-lasting matte color with a built-in primer.',
        price: 500,
        rating: 4.5,
        reviews: 6800,
        image: 'https://www.lakmeindia.com/cdn/shop/files/24846_H-890103098578_1000x.jpg?v=1737700034',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        colors: [
            { name: 'Red Coat', hex: '#C04449' },
            { name: 'Pink Post', hex: '#D87084' },
            { name: 'Mauve Matter', hex: '#A96974' },
            { name: 'Coffee Command', hex: '#8C5A4A' },
        ],
    },
    {
        productId: 10,
        name: 'Infallible 24H Fresh Wear Foundation',
        brand: "L'Oreal Paris",
        description: 'Breathable, full coverage that lasts all day.',
        price: 1200,
        rating: 4.7,
        reviews: 5500,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/940779/82KSSX_8-Y-940779_1.jpg',
        type: 'Foundation',
        category: 'Face',
        colors: [
            { name: 'Porcelain', hex: '#F6E0D1' },
            { name: 'Golden Beige', hex: '#E3C09F' },
            { name: 'Sun Beige', hex: '#D2A176' },
            { name: 'Espresso', hex: '#6D452B' },
        ],
    },
    {
        productId: 11,
        name: 'Fit Me Matte + Poreless Foundation',
        brand: 'Maybelline New York',
        description: 'For a natural, seamless finish.',
        price: 600,
        rating: 4.6,
        reviews: 12500,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/940513/HamotiDxKE-940513_1.jpg',
        type: 'Foundation',
        category: 'Face',
        colors: [
            { name: 'Ivory', hex: '#F3DBC7' },
            { name: 'Classic Ivory', hex: '#EED6BB' },
            { name: 'Sun Beige', hex: '#D9B38F' },
            { name: 'Toffee', hex: '#B88563' },
        ],
    },
    {
        productId: 12,
        name: 'Retro Matte Lipstick',
        brand: 'MAC',
        description: 'Iconic product that made MAC famous.',
        price: 1750,
        rating: 4.9,
        reviews: 9800,
        image: 'https://m.media-amazon.com/images/I/61Ivfv8W14L.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        colors: [
            { name: 'Ruby Woo', hex: '#9B111E' },
            { name: 'Velvet Teddy', hex: '#B58473' },
            { name: 'Mehr', hex: '#C87D81' },
            { name: 'Diva', hex: '#6E262E' },
        ],
    },
    {
        productId: 13,
        name: 'Powder Blush',
        brand: 'MAC',
        description: 'Designed by and for professionals. Applies evenly, adheres lightly.',
        price: 2400,
        rating: 4.8,
        reviews: 4200,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/Sblprro-Q-M.A.C-Matte-Powder-Blush-Mocha-(6g).jpeg',
        type: 'Blush',
        category: 'Cheeks',
        colors: [
            { name: 'Melba', hex: '#E59A80' },
            { name: 'Peaches', hex: '#F0A175' },
            { name: 'Desert Rose', hex: '#C7756B' },
            { name: 'Fleur Power', hex: '#E47D8C' },
        ],
    },
    {
        productId: 15,
        name: 'Voluminous Lash Paradise Mascara',
        brand: "L'Oreal Paris",
        description: 'Voluptuous volume and intense length.',
        price: 999,
        rating: 4.6,
        reviews: 7200,
        image: 'https://static.beautytocare.com/cdn-cgi/image/width=1600,height=1600,f=auto/media/catalog/product//l/-/l-oreal-paris-lash-paradise-volumising-mascara-01-intense-black-6-4ml.jpg',
        type: 'Eyeshadow',
        category: 'Eyes',
        colors: [
            { name: 'Blackest Black', hex: '#000000' },
            { name: 'Black', hex: '#1C1C1C' },
            { name: 'Black Brown', hex: '#3B2A1A' },
        ],
    },
    {
        productId: 16,
        name: 'SuperStay Matte Ink Liquid Lipstick',
        brand: 'Maybelline New York',
        description: 'Flawless matte finish for up to 16 hours.',
        price: 650,
        rating: 4.7,
        reviews: 15000,
        image: 'https://m.media-amazon.com/images/I/315NWHtfujL._SX300_SY300_QL70_FMwebp_.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Liquid Matte',
        colors: [
            { name: 'Lover', hex: '#A9646D' },
            { name: 'Pioneer', hex: '#AF1A2D' },
            { name: 'Voyager', hex: '#6B2428' },
            { name: 'Seductress', hex: '#A46C56' },
        ],
    },
    {
        productId: 17,
        name: 'MACximal Silky Matte Lipstick',
        brand: 'MAC',
        description: 'An icon, reimagined. Silky matte finish with a comfortable feel.',
        price: 2550,
        rating: 4.8,
        reviews: 8500,
        image: 'https://sdcdn.io/mc/mac_sku_NW9M15_3000x3000_0S.png',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        shades: 'Chili, Mehr, Velvet Teddy, Russian Red, Ruby Woo, Whirl, Taupe, Diva, Wig, Mocha, Marrakesh, Lady Danger, Flat Out Fabulous, Brave, Relentlessly Red, All Fired Up, Please Me, Sin, Smoked Almond, D for Danger',
        colors: [
            { name: 'Chili', hex: '#B74136' },
            { name: 'Mehr', hex: '#C87D81' },
            { name: 'Velvet Teddy', hex: '#B58473' },
            { name: 'Russian Red', hex: '#C21807' },
            { name: 'Ruby Woo', hex: '#9B111E' },
            { name: 'Whirl', hex: '#8F5A5A' },
            { name: 'Diva', hex: '#6E262E' },
            { name: 'Lady Danger', hex: '#FF6347' },
            { name: 'Please Me', hex: '#F2A1A8' },
            { name: 'Sin', hex: '#5E2129' },
        ],
    },
    {
        productId: 18,
        name: 'Retro Matte Liquid Lipcolour',
        brand: 'MAC',
        description: 'A lip colour that provides a splash of colour in a liquid-suede, retro matte finish.',
        price: 2800,
        rating: 4.7,
        reviews: 6300,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1147893/0onybwQTd-1147893_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Liquid Matte',
        shades: 'Feels So Grand, Burnt Spice, Fashion Legacy, Topped With Brandy, Dance with Me, Carnivorous, Lady-Be-Good, Quite the Standout, High Drama, Ess-Presso',
        colors: [
            { name: 'Feels So Grand', hex: '#A52A2A' },
            { name: 'Burnt Spice', hex: '#C9866F' },
            { name: 'Fashion Legacy', hex: '#F03A1C' },
            { name: 'Topped With Brandy', hex: '#A86558' },
            { name: 'Dance with Me', hex: '#9E2235' },
            { name: 'Lady-Be-Good', hex: '#E59A80' },
            { name: 'High Drama', hex: '#5A203C' },
        ],
    },
    {
        productId: 19,
        name: 'Powder Kiss Lipstick',
        brand: 'MAC',
        description: 'A weightless moisture-matte lipstick that delivers a blur of soft-focus colour.',
        price: 2550,
        rating: 4.9,
        reviews: 11200,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1124703/oNE_l2oVkO-1124703_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        shades: 'Devoted to Chili, Mull It Over, Burning Love, Style Shocked!, Scattered Petals, Lasting Passion, Mandarin O, Sultry Move, Reverence, Influentially It, Shocking Revelation, Werk, Werk, Werk, Fall in Love',
        colors: [
            { name: 'Devoted to Chili', hex: '#B74136' },
            { name: 'Mull It Over', hex: '#C67B7B' },
            { name: 'Burning Love', hex: '#8A3d54' },
            { name: 'Lasting Passion', hex: '#D94A5B' },
            { name: 'Mandarin O', hex: '#E56E49' },
            { name: 'Werk, Werk, Werk', hex: '#C95B6A' },
            { name: 'Fall in Love', hex: '#E64A85' },
        ],
    },
    {
        productId: 20,
        name: 'Powder Kiss Liquid Lipcolour',
        brand: 'MAC',
        description: 'Whipped, mousse-like texture that delivers soft-focus moisture-matte colour.',
        price: 2700,
        rating: 4.8,
        reviews: 7800,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1082217/2nfim8nqFy-773602567935_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Liquid Matte',
        shades: 'Over the Taupe, Burning Love, Date Maker, Mull It Over, Sorry Not Sorry, Devoted to Chili, Fashion Sweetie, Got a Callback, Make It Fashion!, No Good',
        colors: [
            { name: 'Over the Taupe', hex: '#B18374' },
            { name: 'Mull It Over', hex: '#C67B7B' },
            { name: 'Sorry Not Sorry', hex: '#E5673E' },
            { name: 'Devoted to Chili', hex: '#B74136' },
            { name: 'Fashion Sweetie', hex: '#E2808E' },
        ],
    },
    {
        productId: 21,
        name: 'Lustreglass Sheer-Shine Lipstick',
        brand: 'MAC',
        description: 'A lightweight lipstick with a glossy, sheer finish.',
        price: 2550,
        rating: 4.6,
        reviews: 5400,
        image: 'https://ssbimages.ssbeauty.in/pub/media/catalog/product/images/MAC-SMXF20/MAC-SMXF20_base.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Glossy',
        shades: "Thanks, It's MAC!, Syrup, Lady Bug, PDA, Posh Pit, Hug Me, Giddy, Business Casual, Sellout, Beam There Done That",
        colors: [
            { name: "Thanks, It's MAC!", hex: '#C87D81' },
            { name: 'Syrup', hex: '#B17D84' },
            { name: 'Lady Bug', hex: '#C04449' },
            { name: 'PDA', hex: '#E06D67' },
            { name: 'Posh Pit', hex: '#9E432E' },
            { name: 'Hug Me', hex: '#D29A88' },
        ],
    },
    {
        productId: 22,
        name: 'Amplified Lipstick',
        brand: 'MAC',
        description: 'An ultra-creamy, semi-lustrous finish lipstick.',
        price: 2550,
        rating: 4.7,
        reviews: 6900,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1082148/tNW-W_ebOP-773602051823_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Cream/Satin',
        shades: 'Brick-O-La, Cosmo, Vegas Volt, Dubonnet, Chatterbox, Craving',
        colors: [
            { name: 'Brick-O-La', hex: '#A35352' },
            { name: 'Cosmo', hex: '#C87D81' },
            { name: 'Vegas Volt', hex: '#EF6F5B' },
            { name: 'Dubonnet', hex: '#772C31' },
            { name: 'Chatterbox', hex: '#E5698B' },
            { name: 'Craving', hex: '#C27E86' },
        ],
    },
    {
        productId: 23,
        name: 'Satin Lipstick',
        brand: 'MAC',
        description: 'A creamy, satin-finish lipstick with semi-matte finish.',
        price: 2550,
        rating: 4.8,
        reviews: 8200,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1082174/UPBjD0GLtd-773602048298_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Cream/Satin',
        shades: 'Brave, Mocha, Captive, Spirit, Paramount, Verve',
        colors: [
            { name: 'Brave', hex: '#C68786' },
            { name: 'Mocha', hex: '#9D6F60' },
            { name: 'Captive', hex: '#A35352' },
            { name: 'Spirit', hex: '#B58473' },
            { name: 'Paramount', hex: '#773E3A' },
            { name: 'Verve', hex: '#8F5A5A' },
        ],
    },
    {
        productId: 24,
        name: 'Matte Lipstick',
        brand: 'MAC',
        description: 'The iconic product that made M·A·C famous. A rich, creamy matte finish.',
        price: 2550,
        rating: 4.9,
        reviews: 14500,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1140731/p21KDfV6Dy-1140731_1.jpg',
        type: 'Lipstick',
        category: 'Lips',
        finish: 'Matte',
        shades: 'Chili, Heroine, Lady Danger, Pink Pigeon, Please Me, Ruby Woo',
        colors: [
            { name: 'Chili', hex: '#B74136' },
            { name: 'Heroine', hex: '#702963' },
            { name: 'Lady Danger', hex: '#FF6347' },
            { name: 'Please Me', hex: '#F2A1A8' },
            { name: 'Ruby Woo', hex: '#9B111E' },
        ],
    },

    // === Additional products from user's spreadsheet ===
    {
        productId: 25,
        name: 'Studio Fix Fluid SPF 15 Foundation',
        brand: 'MAC',
        description: 'A modern foundation that provides a natural matte finish with medium to full coverage.',
        price: 4000,
        rating: 4.7,
        reviews: 8900,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/890066/aFo0vJbpBd-M.A.C_Studio_Fix_Fluid_Liquid_Foundation-qiPKa3pBqz.jpeg',
        type: 'Foundation',
        category: 'Face',
        finish: 'Matte',
        shades: 'NC15-NC50, NW15-NW50, C4-C6',
        colors: [
            { name: 'NC15', hex: '#F5D5C0' },
            { name: 'NC25', hex: '#E5C4A8' },
            { name: 'NC35', hex: '#D4A97A' },
            { name: 'NC42', hex: '#C09060' },
            { name: 'NW25', hex: '#D4B8A0' },
            { name: 'NW35', hex: '#C09878' },
        ],
    },
    {
        productId: 26,
        name: 'Studio Radiance Serum-Powered Foundation',
        brand: 'MAC',
        description: 'A serum-powered foundation with radiant, dewy finish and skin-caring benefits.',
        price: 4300,
        rating: 4.6,
        reviews: 4200,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/1131507/TgqKkMYKSg-773602663415_1.jpg',
        type: 'Foundation',
        category: 'Face',
        finish: 'Radiant',
        shades: 'N0-N12, C2-C6, W1-W10',
        colors: [
            { name: 'N4', hex: '#F0D8C0' },
            { name: 'N6', hex: '#E0C4A8' },
            { name: 'C4', hex: '#D8B896' },
            { name: 'W5', hex: '#C8A078' },
        ],
    },
    {
        productId: 27,
        name: 'Studio Fix Powder Plus Foundation',
        brand: 'MAC',
        description: 'A one-step application of powder and foundation with matte finish.',
        price: 4000,
        rating: 4.8,
        reviews: 9500,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/971152/n0Kxl2f-qM-M.A.C-Studio-Fix-Powder-Plus-Foundation-N5-15GM.jpeg',
        type: 'Foundation',
        category: 'Face',
        finish: 'Matte',
        shades: 'NC/NW15-55, C Series',
        colors: [
            { name: 'NC20', hex: '#F0D0B8' },
            { name: 'NC30', hex: '#D8B090' },
            { name: 'NC40', hex: '#C49060' },
            { name: 'NW20', hex: '#E8C8A8' },
        ],
    },
    {
        productId: 28,
        name: 'Powder Blush - Pressed Powder',
        brand: 'MAC',
        description: 'A blush that provides fantastic colour with ease and consistency.',
        price: 2500,
        rating: 4.8,
        reviews: 5600,
        image: 'https://cdn.tirabeauty.com/v2/billowing-snowflake-434234/tira-p/wrkr/products/pictures/item/free/resize-w:1080/Sblprro-Q-M.A.C-Matte-Powder-Blush-Mocha-(6g).jpeg',
        type: 'Blush',
        category: 'Cheeks',
        finish: 'Pressed Powder',
        shades: 'Melba, Gingerly, Mocha, Peaches, Harmony, Coppertone, Fleur Power, Raizin, Pinch Me',
        colors: [
            { name: 'Melba', hex: '#E59A80' },
            { name: 'Gingerly', hex: '#E8A87C' },
            { name: 'Mocha', hex: '#9E7B6B' },
            { name: 'Peaches', hex: '#F0A175' },
            { name: 'Harmony', hex: '#D8A090' },
            { name: 'Fleur Power', hex: '#E47D8C' },
        ],
    },
    {
        productId: 29,
        name: 'Glow Play Blush',
        brand: 'MAC',
        description: 'A cream-to-powder blush that blends into a natural finish.',
        price: 3200,
        rating: 4.7,
        reviews: 3800,
        image: 'https://m.media-amazon.com/images/I/61HKFKEp0bL.jpg',
        type: 'Blush',
        category: 'Cheeks',
        finish: 'Cream-to-Natural',
        shades: 'Blush Please, Cheer Up, So Natural, Grand, Heat Index, That\'s Peachy',
        colors: [
            { name: 'Blush Please', hex: '#F5A0A0' },
            { name: 'Cheer Up', hex: '#E88090' },
            { name: 'So Natural', hex: '#D89080' },
            { name: 'Grand', hex: '#E07868' },
            { name: 'Heat Index', hex: '#E86050' },
            { name: "That's Peachy", hex: '#F8B090' },
        ],
    },
];

const seedProducts = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');

        // Clear existing products
        await Product.deleteMany({});
        console.log('Cleared existing products');

        // Insert new products
        const result = await Product.insertMany(products);
        console.log(`✅ Successfully seeded ${result.length} products`);

        // Log summary by category
        const categories = {};
        result.forEach(p => {
            categories[p.category] = (categories[p.category] || 0) + 1;
        });
        console.log('\nProducts by category:');
        Object.entries(categories).forEach(([cat, count]) => {
            console.log(`  ${cat}: ${count}`);
        });

        // Log summary by brand
        const brands = {};
        result.forEach(p => {
            brands[p.brand] = (brands[p.brand] || 0) + 1;
        });
        console.log('\nProducts by brand:');
        Object.entries(brands).forEach(([brand, count]) => {
            console.log(`  ${brand}: ${count}`);
        });

    } catch (error) {
        console.error('Error seeding products:', error);
    } finally {
        await mongoose.connection.close();
        console.log('\nDatabase connection closed');
    }
};

seedProducts();
